name: auto-merge

on:
  check_suite:
    types:
      - completed
  pull_request:
    types:
      - edited
      - labeled
      - opened
      - ready_for_review
      - reopened
      - synchronize
      - unlabeled
      - unlocked

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: salmanm/action-dependabot-auto-merge@master
        with:
          github-token: ${{github.token}}
