# dependabot[bot]

name: Dependabot Auto Merge

on:
  check_suite:
    types:
      - completed
  pull_request:
    types:
      - edited
      - labeled
      - opened
      - ready_for_review
      - reopened
      - synchronize
      - unlabeled
      - unlocked

jobs:
  worker:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        if: ${{ github.actor == 'salmanm' }}
        uses: actions/github-script@v3
        with:
          script: |
            console.log(context)
          github-token: ${{github.token}}

      - name: Run a one-line script
        run: echo "11"
