name: auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: salmanm/action-dependabot-auto-merge@master
        with:
          github-token: ${{secrets.mytoken}}
